#' add_signalViaMatlab
#'
#' @description Use a Matlab function to derive an extra signal file for each
#' bundle of the Emu database. A new track definition will be added to the
#' database automatically.
#'
#' @details This enables EMU-SDMS users you take advantage of tool boxes and
#' signal processing functions written in Matlab. The Matlab function must meet
#' certain requirements as detailed below, and it will always be run against the
#' entire database.
#'
#' The Matlab function must:
#'
#' - Be defined in a file of its own.
#' - Accept named parameters.
#' - Accept at least the parameters `inputFilename` and `outputFilename`, both
#'   strings.
#' - Use the file at `inputFilename` and produce a new file `outputFilename`;
#'   the new file must be a `.mat` file containing the variables `data`,
#'   `sampleRate`, `startTime`, `units`, and `comment`.
#'
#' The Matlab function can accept more parameters to influence the signal
#' processing. These parameters need not be the same values for the entire
#' database. They can be used, for example, to modify the signal processing
#' algorithms in a speaker-specific way.
#'
#' If `oneMatlabFunctionCallPerFile` is `TRUE`, the function will be called once
#' for every bundle of the database; in that case, all parameters
#' to the Matlab function will be 1x1 matrices. If `oneMatlabFunctionCallPerFile`
#' is `FALSE`, the Matlab function will only be called once for the entire database;
#' in that case, all parameters will be 1xN matrices with N equal to the number
#' of bundles in the database. `add_signalViaMatlab` will create a temporary `.m`
#' script. That script may, for example, contain code like this:
#'
#' ... (examples)
#'
#' The input file will typically be the media file of the bundle, but can be one
#' of the other files stored in the bundle.
#'
#' The output `.mat` files that needs to be written by the Matlab function will
#' be converted – by `emuR` – to `.Rda` file and saved in each bundle folder with
#' the file extension `outputFileExtension`.
#'
#' The working directory of the Matlab function will be the same as that of the
#' current R session, see `getwd()`.
#'
#' You need a working and licensed Matlab instance on your computer. It will be
#' called via `matlabr::run_matlab_code()`.
#'
#' @param emuDBhandle The Emu database to work on.
#' @param matlabFunctionName Name of a Matlab function to use for signal processing.
#' @param outputFileExtension The file extension for the new derived signal file to be created within each bundle.
#' @param trackName The name of the new track that will be created automatically.
#' @param trackColumn The column of data to be used from the result files generated by Matlab. Should usually start with `data$`.
#' @param oneMatlabFunctionCallPerFile Whether to call `matlabFunctionName` once per file (TRUE) or once for the entire database (FALSE).
#' @param inputFileExtension The file extension of the files to operate on. Defaults to the standard media file extension of the current Emu database.
#' @param matlabFunctionParameters Data frame with parameters for `matlabFunctionName`. Needs to contain the columns `session` and `bundle` plus one column for each function parameter. The column names will be used as parameter names. Must contain *one row for every bundle*.
#' @param ...
#'
#' @export
add_signalViaMatlab = function(emuDBhandle,
                               matlabFunctionName,
                               outputFileExtension,
                               trackName,
                               trackColumn,
                               oneMatlabFunctionCallPerFile = TRUE,
                               inputFileExtension = NULL,
                               matlabFunctionParameters = NULL,
                               ...) { # @TODO In doc, for ..., refer to run_matlab_code -> paths_to_add
  # By "using" these variables, we make them required arguments in terms of R UI:
  emuDBhandle
  matlabFunctionName
  outputFileExtension
  trackName
  trackColumn

  if (is.null(inputFileExtension)) {
    DBconfig = load_DBconfig(emuDBhandle)
    inputFileExtension = DBconfig$mediafileExtension
  }

  listOfFiles =
    list_files(emuDBhandle, inputFileExtension) %>%
    mutate(inputFilename        = absolute_file_path,
           outputFilename       = paste(emuDBhandle$basePath,
                                        paste0(session, session.suffix),
                                        paste0(bundle,  bundle.dir.suffix),
                                        paste0(bundle,  ".", outputFileExtension),
                                        sep = .Platform$file.sep),
           intermediateDir      = paste(tempdir(),
                                        "add_signalViaMatlab",
                                        emuDBhandle$UUID,
                                        paste0(session, session.suffix),
                                        sep = .Platform$file.sep),
           intermediateFilename = paste(intermediateDir,
                                        paste0(bundle, ".mat"),
                                        sep = .Platform$file.sep))

  fs::dir_create(path = listOfFiles$intermediateDir, recurse = TRUE)

  filenameParameters =
    listOfFiles %>%
    select(session, bundle, inputFilename, outputFilename = intermediateFilename) %>%
    encodeStringsAsMatlabLiterals()

  if (is.null(matlabFunctionParameters)) {
    matlabFunctionParameters = tibble::tibble(session = character(), bundle = character())
  } else {
    matlabFunctionParameters =
      matlabFunctionParameters %>%
      encodeStringsAsMatlabLiterals()
  }

  matlabCommands =
    left_join(filenameParameters,
              matlabFunctionParameters,
              by = c("session", "bundle")) %>%
    select(-session, -bundle)

  if (oneMatlabFunctionCallPerFile) {
    matlabCommands =
      matlabCommands %>%
      makeKeyValuePairs() %>%
      unite("allParameters",
            everything(),
            sep = ", ") %>%
      mutate(command = paste0(matlabFunctionName,
                              "(",
                              allParameters,
                              ")"))
  } else {
    matlabCommands =
      matlabCommands %>%
      summarise(across(everything(),
                       ~ paste0(.x, collapse = ", ")),
                across(everything(),
                       ~ paste0("[", .x, "]"))) %>%
      makeKeyValuePairs() %>%
      unite("allParameters",
            everything(),
            sep = ", ") %>%
      mutate(command = paste0(matlabFunctionName,
                              "(",
                              allParameters,
                              ")"))
  }

  matlabr::run_matlab_code(matlabCommands$command,
                           endlines = TRUE,
                           ...)

  convertMatlabIntermediateFilesToRda(listOfFiles)

  add_ssffTrackDefinition(emuDBhandle = emuDBhandle,
                          name = trackName,
                          columnName = trackColumn,
                          fileExtension = outputFileExtension,
                          fileFormat = "Rda")
}


# Converts .mat files as stored by `add_signalViaMatlab()` to .Rda files.
#
# The argument files must be a data frame with the columns `intermediateFilename`
# and `outputFilename`. The `.mat` file must exist at the intermediate path, and
# the `.Rda` file will be created at the output path.
#
convertMatlabIntermediateFilesToRda = function(files) {
  for (i in rownames(files)) {
    currentFile = files[i,]

    rawData    = R.matlab::readMat(currentFile$intermediateFilename)

    data       = rawData$data
    units      = rawData$units
    sampleRate = rawData$sampleRate[1,1]
    startTime  = rawData$startTime[1,1]
    comment    = rawData$comment[1,1]

    save(data,
         units,
         sampleRate,
         startTime,
         comment,
         file = currentFile$outputFilename)
  }
}


# Expects a data frame and transforms all character-typed columns except those
# named "session" or "bundle".
#
# The transformation includes:
# - escaping all double quotes (") in the values as two double quotes ("")
# - adding one double quote to the beginning and end of each value
#
encodeStringsAsMatlabLiterals = function(matlabFunctionParameters) {
  for (column in colnames(matlabFunctionParameters)) {
    if (column == "session" || column == "bundle") {
      next
    }

    columnType = typeof(pull(matlabFunctionParameters, column))

    if (columnType == "character") {
      matlabFunctionParameters[column] =
        str_replace_all(pull(matlabFunctionParameters, column),
                        '"',
                        '""')

      matlabFunctionParameters[column] =
        paste0('"',
               pull(matlabFunctionParameters, column),
               '"')
    }
  }

  return(matlabFunctionParameters)
}


# Expects a data frame and transforms all columns except those named "session"
# or "bundle".
#
# The transformation consists of prepending each value with "columnName=".
#
makeKeyValuePairs = function(data) {
  for (column in colnames(data)) {
    if (column == "session" || column == "bundle") {
      next
    }

    data[column] = paste0(column,
                          "=",
                          pull(data, column))
  }

  return(data)
}
